### ISSUE TITLE
fix(layout): remove horizontal scroll of the page

### ISSUE THREAD

**Issue by beatrizsmerino** [beatrizsmerino/vue-users#122]
# fix(layout): remove horizontal scroll of the page

| ⏱️ Estimate | 📊 Priority | 📏 Size | 📅 Start | 📅 End |
|---------|-------------|---------|----------|--------|
| 1h      | P2          | XS      | 11-10-2021 | 16-10-2021 |

### Horizontal scroll
| Current | Expected |
|:------:|:------:|
| <img width="400" alt="Horizontal scroll caused by negative margins on users-list__wrapper" src="https://user-images.githubusercontent.com/14045148/136837719-a10ae336-da51-4cbb-86d2-65eb16391a91.png" /> <img width="400" alt="Element overflowing viewport width causing horizontal scrollbar" src="https://user-images.githubusercontent.com/14045148/136837470-0d102879-76a2-4e11-9e2b-c83de9c6431e.png" /> | <img width="400" alt="Fix: replace negative margin with margin-bottom" src="https://user-images.githubusercontent.com/14045148/136864949-f57a1fca-d7bd-4fbc-8e2e-5fc453655bb8.png" /> |

### `eslint.CLIEngine` error
| Current | Expected |
|:------:|:------:|
| <img width="400" alt="Error: eslint.CLIEngine is not a constructor during build" src="https://user-images.githubusercontent.com/24830039/136842564-70ecd62e-9bfa-436d-adfa-b1a9f4876f78.png" /> | <img width="400" alt="Server running without errors with npm run serve" src="https://user-images.githubusercontent.com/14045148/136839522-34de58e3-4395-420e-ba4d-7299f82368bc.png" /> |

## 📝 Summary

- The page has an unwanted horizontal scrollbar that allows scrolling sideways
- Some element is overflowing the viewport width, causing the horizontal scroll to appear

## 💡 Why this bug?

- An element in the page has a width or margin that exceeds the viewport width (100vw or 100%)
- Common causes include elements with `width: 100vw` not accounting for the vertical scrollbar, padding/margin pushing content beyond the container, or absolute/fixed positioned elements extending past the viewport edge

## ✅ Expected behavior

- The page should only have vertical scrolling
- No horizontal scrollbar should be visible
- All content should fit within the viewport width

## 📋 Steps

- [x] Identify which element causes the horizontal overflow using browser DevTools (inspect elements and look for those extending beyond the viewport)
- [x] Fix the overflow by adjusting the element's width, margin or positioning
- [x] Add `overflow-x: hidden` to the body or root element as a fallback if needed

## 🧪 Tests

- [x] No horizontal scrollbar is visible on any page
- [x] All content fits within the viewport width
- [x] Layout is correct on different screen sizes

### Files modified

- [x] SCSS styles (overflow fix)

**Comment by od-c0d3r** [comment]
hey @beatrizsmerino, can i work on this !?

**Comment by beatrizsmerino** [comment]
> what do u think about this #126 ?

sorry, I'm checking the dependencies and adding the eslint and prettier configuration.

**Comment by beatrizsmerino** [comment]
> what do u think about this #126 ?

OK I think that the error it is fixed.
Please can you delete and clone the project again?
I have removed the last update of `eslint 8.0.0` dependency, it was not working properly. And I added the `eslint` and `prettier` configuration, you can fix the errors by running the command `npm run lint`.
